version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: "jc21/mariadb-aria:latest"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD: "npm"
      - MYSQL_DATABASE: "npm"
      - MYSQL_USER: "npm"
      - MYSQL_PASSWORD: "npm"
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  default:
    external:
      name: proxy

healtcheck:
  test: ["CMD", "/bin/check-healt"]
  interval: 10s
  timeout: 3s
